# name: Create Release Tag

# on:
#   push:
#     tags:
#       - '*'

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check Out Code
#         uses: actions/checkout@v2

#       - name: Create Release Tag
#         run: |
#           ./create-release-tag.sh
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
